clc;close all;clear all;
img=imread('cameraman.tif');
figure,subplot(2,3,1),imshow(img),title('实验人：赵奕翔'),xlabel('(a)原图');
img_noise=double(imnoise(img,'gaussian',0.06));
subplot(2,3,2),imshow(img_noise,[]),title('实验人：赵奕翔'),xlabel('(b)高斯噪声污染图像');
img_mean=imfilter(img_noise,fspecial('average',3));
subplot(2,3,3),imshow(img_mean,[]),title('实验人：赵奕翔'),xlabel('(c)用3x3算数均值滤波器');
img_mean=exp(imfilter(log(img_noise+1),fspecial('average',3)));
subplot(2,3,4),imshow(img_mean,[]),title('实验人：赵奕翔'),xlabel('(d)用3x3几何均值滤波器');
Q=-1.5;
img_mean=imfilter(img_noise.^(Q+1),fspecial('average',3))./imfilter(img_noise.^Q,fspecial('average',3));
subplot(2,3,5),imshow(img_mean,[]),title('实验人：赵奕翔'),xlabel('(e)Q=-1.5的逆谐波滤波器滤波');
Q=1.5;
img_mean=imfilter(img_noise.^(Q+1),fspecial('average',3))./imfilter(img_noise.^Q,fspecial('average',3));
subplot(2,3,6),imshow(img_mean,[]),title('实验人：赵奕翔'),xlabel('(f)Q=1.5的逆谐波滤波器滤波');
